// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQGcKQxClz97X2p0Fcxy97K2P0aAstehc',
    appId: '1:799109632704:android:ff43625bc1c263418e5325',
    messagingSenderId: '799109632704',
    projectId: 'chatter-23fb0',
    storageBucket: 'chatter-23fb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK9Jr0gFU5GhDDPyy0n3uikmELn1woNH8',
    appId: '1:799109632704:ios:5a8bce4b5427dbe38e5325',
    messagingSenderId: '799109632704',
    projectId: 'chatter-23fb0',
    storageBucket: 'chatter-23fb0.appspot.com',
    androidClientId: '799109632704-rku7nb84o0gttfee33m1vbnoi1ls48m8.apps.googleusercontent.com',
    iosClientId: '799109632704-a4f8rgjcn2lv06ib4hlr5l6r5ectjukl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
